// Code generated by cmd/cgo; DO NOT EDIT.

//line /opt/go/sample/cgo/go/ext2/main.go:1:1
package main

//void SayHello(_GoString_ s);
import _ "unsafe"

import (
        "fmt"
)

func main() {
        ( /*line :11:9*/_Cfunc_SayHello /*line :11:18*/)("Hello, World\n")
}

//export SayHello
func SayHello(s string) {
        fmt.Print(s)
}
